ViewModels/Test.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmpty.ViewModels
{
    public class Test
    {
    }
}

Controllers/MyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCEmpty.Controllers
{
    public class MyController : Controller
    {
        public ViewResult Home()
        {
            ViewBag.Date = DateTime.Now.ToString();
            return View();
        }
        public ViewResult About()
        {
            ViewBag.Title = "Lucian testar viewbag";
            ViewBag.Date = DateTime.Now.ToString();
            return View();
        }
        public ViewResult Contact()
        {
            ViewBag.Date = DateTime.Now.ToString();
            return View();
        }
        public ViewResult Projects()
        {
            ViewBag.Date = DateTime.Now.ToString();
            return View();
        }
    }

}

Views/My/About.cshtml
<h1>Bamboo</h1>

<p>Bamboo is a restaurant in Sweden...</p>

Views/My/Contact.cshtml
<div class="container">
    <div class="row">
        <div>
            Address: Grevegatan 14, 424 14 Hovås
        </div>
        <div>
            Phone: + 46 (0)706 885 332
        </div>
        <div>
            Website:  <a href="bamboo">Bamboo.se</a>
        </div>
        <div>
            Program: Mon to Sat: 09:30 AM - 10.30 PM
        </div>
    </div>
</div>

Views/My/Home.cshtml
<h1>Welcome to Bamboo</h1>
<p>At our restaurant, you can choose food from a wide variety of ...</p>

Views/My/Projects.cshtml
<h1>Projects</h1>

<ul>
    <li><a href="https://github.com/Lussekatten/Hangman">Hangman</a></li>
    <li><a href="https://github.com/Lussekatten/Vending2022">Vending machine</a></li>
</ul>

Views/Shared/_Layout.cshtml
<html>
<head>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<!-- Template Main CSS File -->

<link rel="stylesheet" type="text/css" href="~/lib/bootstrap/css/bootstrap.css">
<link href="~/content/site.css" rel="stylesheet">

<title>@ViewBag.Title</title>
</head>
<body>
    <div class="container mt-2">
        <img src="~/images/logo.png" class="logo" alt="företagets logotyp">
        <ul class="nav">
            <li class="nav-item">
                <a asp-controller="My" asp-action="Home">Home</a>
            </li>
            <li class="nav-item">
                <a asp-controller="My" asp-action="About">About</a>
            </li>
            <li class="nav-item">
                <a asp-controller="My" asp-action="Projects">Projects</a>
            </li>
            <li class="nav-item">
                <a asp-controller="My" asp-action="Contact">Contact</a>
            </li>
        </ul>
    </div>
    <div class="container">
        <div>
            @RenderBody()
        </div>
    </div>
    <footer>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            @ViewBag.Date &nbsp;&nbsp;
            Lucian Ralea
        </div>
    </footer>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</body>
</html>